version: '3.9'
services:
    db:
        image: mysql:latest
        volumes:
            - db_data:/var/lib/mysql:delegated
        environment:
            MYSQL_ROOT_PASSWORD: somewordpress
            MYSQL_DATABASE: password
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress

    wordpress:
        depends_on:
        - db
        image: wordpress:php8.1-fpm-alpine
        deploy:
            resources:
                limits:
                    cpus: "1.0"
                    memory: 1G
                reservations:
                    cpus: "0.5"
                    memory: 512M
        volumes:
            - wpvol:/var/www/html:delegated
        ports:
        - "8000:80"
        environment:
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress
            WORDPRESS_DB_NAME: zika

    apache:
        image: seu-user/sua-imagem:sua-tag
        volumes:
            - ./apache/site.conf:/etc/apache2/sites-available/000-default.conf
            - ./apache/apache2.conf:/etc/apache2/apache2.conf
            - wpvol:/var/www/wordpress:delegated
            - ./wordpress/.htaccess:/var/www/wordpress/.htaccess
        ports:
        - "80:80"
        environment:
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress
            WORDPRESS_DB_NAME: password

volumes:
    db_data:
    wpvol:
